### ISSUE TITLE
Specification change about Google Maps APIs

### ISSUE THREAD

**Issue by Hoshock** [astropenguin/azely#2]
Google Maps APIs cannot be used without an API key since July 2018 and azely outputs an error when it requests the location information from Google Maps.

**Comment by astropenguin** [comment]
Hi @Hoshock, I am very sorry for not fixing it for such a long time!
Now I released azely v0.4.3, which is redevelopment of entire codes.
I changed default map provider from Google Maps to OpenStreetMap
and now azely seems to work without API keys.

Here is some examples for demonstration of azely v0.4.3.
https://colab.research.google.com/drive/1kJWJVydE-018nHIyrYrTS209UtUvGDFk
